# -*- coding: utf-8 -*-
"""etl_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zem_PFxIIOtXBOt4L_O8qYeYnuGu8IKN
"""

from google.colab import files
uploaded = files.upload()

!mkdir -p data/source
!unzip -o source.zip -d data/source
!ls data/source

import glob
import pandas as pd
import xml.etree.ElementTree as ET
from datetime import datetime

# -------------------------------
#  Logging Function
# -------------------------------
def log_progress(message):
    """Log progress with timestamp"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open("log_file.txt", "a") as f:
        f.write(f"{timestamp} - {message}\n")
    print(f"{timestamp} - {message}")

# -------------------------------
#  Extraction Functions
# -------------------------------
def extract_from_csv(file):
    return pd.read_csv(file)

def extract_from_json(file):
    return pd.read_json(file, lines=True)

def extract_from_xml(file):
    tree = ET.parse(file)
    root = tree.getroot()
    rows = []
    for person in root.findall("person"):
        name = person.find("name").text
        height = float(person.find("height").text)
        weight = float(person.find("weight").text)
        rows.append({"name": name, "height": height, "weight": weight})
    return pd.DataFrame(rows)

def extract():
    """Extract from all CSV, JSON, XML files"""
    extracted_data = pd.DataFrame(columns=["name", "height", "weight"])

    for csvfile in glob.glob("data/source/*.csv"):
        extracted_data = pd.concat([extracted_data, extract_from_csv(csvfile)], ignore_index=True)

    for jsonfile in glob.glob("data/source/*.json"):
        extracted_data = pd.concat([extracted_data, extract_from_json(jsonfile)], ignore_index=True)

    for xmlfile in glob.glob("data/source/*.xml"):
        extracted_data = pd.concat([extracted_data, extract_from_xml(xmlfile)], ignore_index=True)

    return extracted_data

# -------------------------------
#  Transformation Function
# -------------------------------
def transform(data):
    """Convert inches → meters, pounds → kilograms"""
    data["height"] = round(data["height"] * 0.0254, 2)   # inches → meters
    data["weight"] = round(data["weight"] * 0.45359237, 2)  # pounds → kg
    return data

# -------------------------------
#  Load Function
# -------------------------------
def load(data, target_file):
    data.to_csv(target_file, index=False)

# -------------------------------
#  ETL Pipeline Execution
# -------------------------------
def run_etl():
    log_progress("ETL Job Started")

    log_progress("Extraction phase Started")
    extracted = extract()
    log_progress("Extraction phase Ended")

    log_progress("Transformation phase Started")
    transformed = transform(extracted)
    log_progress("Transformation phase Ended")

    log_progress("Loading phase Started")
    load(transformed, "transformed_data.csv")
    log_progress("Loading phase Ended")

    log_progress("ETL Job Ended")

# Run the pipeline
run_etl()

# Show logs
!cat log_file.txt

# Preview transformed data
import pandas as pd
pd.read_csv("transformed_data.csv").head()

import pandas as pd

df = pd.read_csv("transformed_data.csv")
print("Shape of dataset:", df.shape)
print("\nSummary statistics:")
print(df.describe())

print("\nSample rows:")
print(df.head(10))

from google.colab import files

# Download the transformed CSV
files.download("transformed_data.csv")

# Download the log file
files.download("log_file.txt")